#cloud-config

# ref. https://www.zombiezen.com/blog/2021/08/tailscale-google-container-optimized-os/

write_files:
  - path: /etc/systemd/system/tailscaled.service
    content: |
      [Unit]
      Description=Tailscale node agent
      Documentation=https://tailscale.com/kb/
      Wants=network-pre.target
      After=network-pre.target NetworkManager.service systemd-resolved.service

      [Service]
      ExecStartPre=/mnt/disks/tailscale/tailscaled --cleanup
      ExecStart=/mnt/disks/tailscale/tailscaled \
        --state=/var/lib/tailscale/tailscaled.state \
        --socket=/run/tailscale/tailscaled.sock \
        --port 41641
      ExecStopPost=/mnt/disks/tailscale/tailscaled --cleanup

      Restart=on-failure

      RuntimeDirectory=tailscale
      RuntimeDirectoryMode=0755
      StateDirectory=tailscale
      StateDirectoryMode=0750
      CacheDirectory=tailscale
      CacheDirectoryMode=0750
      Type=notify

      [Install]
      WantedBy=multi-user.target

  - path: /tmp/install-tailscale.sh
    permissions: 0644
    owner: root
    content: |
      #!/bin/bash
      set -euo pipefail
      VERSION="1.64.0"
      DEST="/mnt/disks/tailscale"
      TMPDIR=/var/tmp

      dirname="tailscale_$${VERSION}_amd64"
      tarname="$${dirname}.tgz"
      if [[ ! -e "$TMPDIR/$tarname" ]]; then
        mkdir -p "$TMPDIR"
        download_url="https://pkgs.tailscale.com/stable/$tarname"
        echo "Downloading $download_url" 1>&2
        curl -fsSLo "$TMPDIR/$tarname" "$download_url"
      fi
      mkdir -p "$DEST"
      tar \
        -xzf "$TMPDIR/$tarname" \
        -C "$DEST" \
        --strip-components=1 \
        "$dirname/tailscale" \
        "$dirname/tailscaled"

runcmd:
  - systemctl daemon-reload
  - mkdir /mnt/disks/tailscale
  - mount -t tmpfs tmpfs /mnt/disks/tailscale
  - bash /tmp/install-tailscale.sh
  - systemctl start tailscaled.service
  - /mnt/disks/tailscale/tailscale up --authkey "${tailscale_auth_key}" -ssh
  - /mnt/disks/tailscale/tailscale set --auto-update
