version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "12:00"
      timezone: "Asia/Tokyo"
    assignees:
      - "notomo"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "12:00"
      timezone: "Asia/Tokyo"
    assignees:
      - "notomo"

  - package-ecosystem: "terraform"
    directory: "/infra/production"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "12:00"
      timezone: "Asia/Tokyo"
    assignees:
      - "notomo"

  - package-ecosystem: "terraform"
    directory: "/infra/admin"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "12:00"
      timezone: "Asia/Tokyo"
    assignees:
      - "notomo"
    groups:
      hashicorp-google-providers:
        patterns:
          - "hashicorp/google"
          - "hashicorp/google-beta"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "12:00"
      timezone: "Asia/Tokyo"
    assignees:
      - "notomo"
