version: "3"

services:

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    env_file:
      - influxdb.env
    volumes:
      - .local/influxdb:/var/lib/influxdb2
