version: "3"

services:

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "127.0.0.1:8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: "setup"
      DOCKER_INFLUXDB_INIT_USERNAME: "admin"
      DOCKER_INFLUXDB_INIT_PASSWORD: "example-password"
      DOCKER_INFLUXDB_INIT_ORG: "example-org"
      DOCKER_INFLUXDB_INIT_BUCKET: "gmailagg"
    volumes:
      - .local/influxdb:/var/lib/influxdb2
