name: ci
on:
  push:
    branches:
      - '*'
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
      - '.github/workflows/ci.yml'
  pull_request:

env:
  GO_VERSION: '1.23'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: make test TEST_OPTS=-race
      - run: make lint
