name: docker image push
on:
  push:
    branches:
      - 'main'
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
      - '.github/workflows/docker-image-push.yml'
      - 'infra/start.sh'
      - 'Dockerfile'

env:
  GO_VERSION: '1.21'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/647706074962/locations/global/workloadIdentityPools/gmailagg-pool/providers/github-actions
          service_account: gmailagg-delivery@gmailagg.iam.gserviceaccount.com

      - uses: google-github-actions/setup-gcloud@v1

      - run: make setup_docker_auth
      - run: make push
