name: docker check
on:
  push:
    paths:
      - 'Dockerfile'
      - 'Makefile'
      - '.github/workflows/docker-check.yml'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: make docker_check
