name: terraform plan
on:
  push:
    branches:
      - '*'
  pull_request:

defaults:
  run:
    working-directory: ./infra

jobs:
  plan:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/647706074962/locations/global/workloadIdentityPools/gmailagg-pool/providers/gmailagg-gh-provider
          service_account: gmailagg-delivery@gmailagg.iam.gserviceaccount.com

      - uses: hashicorp/setup-terraform@v2

      - run: terraform init
      - run: terraform validate
      - run: terraform plan
