name: terraform plan
on:
  push:
    branches:
      - '*'
    paths:
      - 'infra/**'
      - '.github/workflows/terraform-plan.yml'
  pull_request:
    paths:
      - 'infra/**'
      - '.github/workflows/terraform-plan.yml'

defaults:
  run:
    working-directory: ./infra/production

jobs:
  plan_production:
    runs-on: ubuntu-latest

    concurrency:
      group: terraform-production
      cancel-in-progress: false

    defaults:
      run:
        working-directory: ./infra/production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4

      - run: |
          terraform_version=$(../terraform_version.sh)
          echo "TERRAFORM_VERSION=${terraform_version}" >> "$GITHUB_ENV"

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/647706074962/locations/global/workloadIdentityPools/gmailagg-pool/providers/github-actions
          service_account: gmailagg-delivery@gmailagg.iam.gserviceaccount.com

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - run: terraform init
      - run: terraform validate

      - run: terraform plan -detailed-exitcode
        env:
          TAILSCALE_TAILNET: ${{ secrets.TAILSCALE_TAILNET }}
          TAILSCALE_API_KEY: ${{ secrets.TAILSCALE_API_KEY }}

  validate_admin:
    runs-on: ubuntu-latest

    concurrency:
      group: terraform-admin
      cancel-in-progress: false

    defaults:
      run:
        working-directory: ./infra/admin

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4

      - run: |
          terraform_version=$(../terraform_version.sh)
          echo "TERRAFORM_VERSION=${terraform_version}" >> "$GITHUB_ENV"

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/647706074962/locations/global/workloadIdentityPools/gmailagg-pool/providers/github-actions
          service_account: gmailagg-delivery@gmailagg.iam.gserviceaccount.com

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - run: terraform init
      - run: terraform validate
